# Generated by Django 6.1.1 on 2026-09-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potrawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rodzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grzyby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
                ('potoczna', models.TextField()),
                ('jadalny', models.TextField()),
                ('miesiac_zbierania', models.TextField()),
                ('potrawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzybyapp.potrawa')),
                ('rodzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzybyapp.rodzina')),
            ],
        ),
    ]
